### ISSUE TITLE
[FR] Brightness Curves

### ISSUE THREAD

**Issue by CraftoHohenvels** [The-EG/OctoPrint-CameraSettings#210]
**Introduction**
I recently setup OctoPrint with a Webcam for my 3D printer. Sadly I am unable to provide decent lighting conditions, so I resorted to this plugin. It already helped a lot to improve the image quality, but all the tweaking I have done I sadly still have the problem, that certain areas are too dark...

**Description of Desired Feature**
I would want to see a feature to tweaking the brightness using some kind of curves in order to boost the brightness in dark areas, but decrease it in already bright areas.

**Who would use it?**
I see many people like me using such a feature. Either because their light situation is really bad or just because you want to improve your already decent image quality

**Addition**
I haven't seen another plugin implement this (heck I haven't found another plugin allowing you to tweak your camera like this). I somewhat doubt that webcams have such features, so I would say it would have to be a software only implementation

**Comment by The-EG** [comment]
Hi, thanks for giving the plugin a try. Unfortunately, this plugin only exposes what the camera itself is capable of and can't introduce new features.
What you are describing would not be possible to implement in this plugin because it would either need to be implemented on the camera itself or in the streaming application.
