### ISSUE TITLE
[BUG] Presets not Saving / Loading

### ISSUE THREAD

**Issue by Durahl** [The-EG/OctoPrint-CameraSettings#57]
Greetings!

I'm kinda having a problem with either understanding or making use of the Presets feature in this Plugin.

I'm using the Plugin to control a **Logitech BRIO** on a Raspberry Pi4 for which I _think_ I have saved a Preset:
![Preset](https://i.imgur.com/6VIdZif.png)
My understanding from what is currently selected it should load **all** of the settings ( Checkboxes **and** Sliders ) made in the upper portion of the UI upon starting the OctoPrint.

After a power loss ( me just turning off the Printer ) though what happens is it simply ignoring to load the **Slider** portions of Start Preset and reverting to Defaults usually ending in an Out of Focus and Out of While Balance situation? 🤔

Am I missing something? 🤨

**Comment by The-EG** [comment]
Not sure if there's an actual issue here or not and there was no reply, so I'm closing this. If there is an issue and you can provide more information, please re-open.

**Comment by GitHubGoody** [comment]
@The-EG If it's ok with you, I'd like to re-open this based on what I recorded in this video https://youtu.be/L9LqiyX_BTY.

Thank you for your work on this plugin

**Comment by The-EG** [comment]
Ok, based on your video the 'load' feature may have issues. I will say that the load button there only load it once, so if you need a value of 3 for the startup settings to work, then that could be part of the issue. 

What would also be helpful is providing me a debug log. Open OctoPrint settings, go to Logging and add a debug entry for this plugin: 
![image](https://user-images.githubusercontent.com/7342077/149186269-1acfa7d2-3c5d-40ef-9dca-33992b58a196.png)

Then, do the affected behavior (ie. repeat your steps in the video), then go back to the Logging page in settings and download `octoprint.log` and attach it here. After that you can remove the debug entry again.

**Comment by GitHubGoody** [comment]
OK, here's the log. I tried to stick to the same steps as in the video. The one notable difference was the webcam did zoom back out after reverting back to the "Center 1x" preset when I tried it before clicking Save after clicking the down arrow to save the "Center 2x" preset. Then, at the end, I tried a couple preset switches for the log to capture, but the webcam didn't switch back to 2x. I'm happy to do it again and record another video this time if that would help more. Just let me know. ;-)

**Comment by The-EG** [comment]
I finally had a chance to look through this. I'm not seeing any failures to set the settings and it's clearly loading the preset and setting the settings, one by one. I do think the UI might be getting out of sync after a load though, so even if settings are being applied, the UI is probably not showing it immediately.

I'm going to try having the 'load' function apply the settings the same number of times that the 'startup' function does and also fixup the UI being out of sync.

I should have a branch to test soon.

**Comment by The-EG** [comment]
Ok, please give the `fixes/settings-load` branch a try. You can do that by going to the OctoPrint plugin manager and installing from this URL:
https://github.com/The-EG/OctoPrint-CameraSettings/archive/refs/heads/fixes/settings-load.zip

You don't need to uninstall, it will just update it to that version.

I do want to point out again: if you've saved a preset (typed the name in, the pressed the save button next to that box), it doesn't actually save that information until you click the 'Save' button at the bottom of the window. If you were to load that preset before clicking the bottom save button it will not work, although you also won't get an error message. I suspect this may be a factor in what's going on too.

I'm aware that this is *VERY* misleading. Unfortunately, I have to work within how OctoPrint manages the settings. When you click the first 'save' it saves it to the UI, and the rest of the UI knows its there (or changed if you saved over an existing setting). But the server doesn't know about that until you click the main 'Save' button on the settings window. The setting the actual settings and everything is handled by the server, so it has to be told about the settings before it can do that.

I've experimented with trying to make that process work better, but it's really a bit at odd with how the entire settings window is expected to work: you can modify settings all you want and then either discard the changes or save them, as a whole. Forcing the save to happen when you click the first 'save' button would also be misleading because it would save *ALL* settings that you had changed up to that point, including from other plugins or OctoPrint itself. And, sending just the preset to the backend and saving the settings there triggers a warning on the UI because it detects that settings have changed while the window was open.

In any case, it's not ideal, but I do want to get the profile loading working at least, within the above limitations anyway

**Comment by The-EG** [comment]
This is also available for testing in 0.3.2rc1.
