### ISSUE TITLE
[BUG] Spagetti Detective Camera Settings are locked?

### ISSUE THREAD

**Issue by minguezdo** [The-EG/OctoPrint-CameraSettings#64]
**Observed behavior**
What is happening or not working?
Camera settings seems to be locked when using spagetti detective
**Expected behavior**
What should be happening?
camera settings should also apply with spagetti detective
**OctoPrint Version**
What version of OctoPrint are you using?
Version 1.7.2
**CameraSettings Plugin Version**
What version of this plugin are you using?
 0.3.0
**Camera**
What camera are you using?
Elektreks IR Camera
**Linux/OctoPi**
What Linux distribution/image is this running on? If you are unsure, it is probably OctoPi. If OctoPi, what version?
Version 0.18.0, running on Raspberry Pi Zero 2 Rev 1.0
**Other Plugins**
Do you have any other plugins that may be modifying the camera stream (ie, The Spaghetti Detective)?
Access Anywhere - The Spaghetti Detective (1.8.6)

**Comment by The-EG** [comment]
Unfortunately, this plugin is not compatible with The Spaghetti Detective premium streaming.

This is stated on the [plugin page](https://plugins.octoprint.org/plugins/camerasettings/) and the [readme of this repo](https://github.com/The-EG/OctoPrint-CameraSettings)

Additionally that's why I specifically ask if you are using that plugin on the bug template that you just filled out.

This isn't anything I can control, since TSD takes control of the camera and does it's own thing. The two are not compatible and it's not something I can fix from my side.

Note: if you are within the free trial period, you have 'premium' features even if you haven't signed up for it and the above all apply.
