### ISSUE TITLE
Installation on Android fails for missing v4l2-ctl

### ISSUE THREAD

**Issue by embcla** [The-EG/OctoPrint-CameraSettings#86]
**Observed behavior**
Camera Settings
Could not load camera controls:v4l2-ctl not installed

**Expected behavior**
That everything workes

**OctoPrint Version**
1.8.4

**CameraSettings Plugin Version**
0.4.0

**Camera**
Samsung Galaxy S7 rear camera

**Linux/OctoPi**
Octo4a 1.1.2

**Other Plugins**
nope

isn't the dependency handled automatically by the plugin manager?

**Comment by The-EG** [comment]
> isn't the dependency handled automatically by the plugin manager?

The plugin manager handles the *Python* dependencies, of which this plugin has none outside of what would normally already be present for OctoPrint.

Installing the `v4l2-ctl` program will vary by system. The FAQ for that error message describes how to install it for most Linux systems: https://github.com/The-EG/OctoPrint-CameraSettings/blob/main/docs/faq.md#i-get-an-error-v4l2-ctl-not-installed

However, Android is not 'most Linux systems.' I do not believe that the camera has Video4Linux support on Android and I'm not sure if it would even be possible to install `v4l-utils`.

Unfortunately, OctoPrint will let you install this plugin on Octo4A because it reports the system as 'Linux,' but as far as I am aware, it is not compatible with that setup. You will likely need to control the camera settings through whatever app you are using to stream it.
