### ISSUE TITLE
[BUG] Plugin does not save camera settings

### ISSUE THREAD

**Issue by linuxdudeg** [The-EG/OctoPrint-CameraSettings#94]
I configure my Logitech C920 as I would like to have it, click on Save. The next time I start Octoprint it has reverted to the default settings. I also tried putting a name in Preset and saving this, but it does not appear in the combobox to select for startup preset.

From what I understand this plugin replaces the manual startup script to configure the camera using the v4l2-ctl program. So when I start Octoprint it would restore the settings I previously saved

**OctoPrint Version**
OctoPrint 1.8.6

**CameraSettings Plugin Version**
Camera Settings (0.4.1)

**Camera**
Logitech C920s

**Linux/OctoPi**
OctoPi 0.18.0

**Other Plugins**
No other plugins modify the camera settings

**Comment by The-EG** [comment]
Unfortunately, due to how OctoPrint stores settings, the presets and save buttons are a bit unintuitive.

First, setup your settings as you have. Then type a name into the box next to 'Preset' and click the save button next to that, not the save button at the bottom of the OctoPrint settings.
![image](https://user-images.githubusercontent.com/7342077/205053928-a2991dd1-03d6-44a3-8783-74adf76656bb.png)

At that point, you should see that a new preset appears in the list below and it should be available to pick from the list. If not, hit the save button at the bottom of the settings window and come back.

*THEN*, set your startup preset and **most importantly** press the save button at the bottom of the OctoPrint settings window afterward. If you don't hit save that last time, it will not save the startup preset.

Annoying, yes, but it has to do with how OctoPrint moves settings around between the front end (the web UI) and the server.
